swagger: "2.0"
info:
  title: service-parrot
  description: it's parrots
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /post-parrot/{name}/{breed}/{colour}:
    post:
      tags:
      - parrot
      summary: add-parrot parrot
      operationId: parrot#add-parrot
      parameters:
      - name: name
        in: path
        description: Parrot name
        required: true
        type: string
      - name: breed
        in: path
        description: Parrot breed
        required: true
        type: string
      - name: colour
        in: path
        description: Parrot colour
        required: true
        type: string
      responses:
        "201":
          description: Created response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
